version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    working_directory: ~/repo
    environment:
      BRANCH: develop
      TARGET_REPO: 3mmasun/3mmasun.github.io
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              echo -e "Starting to deploy to Github Pages\n"
              cd ~/repo

              git config user.name "$USER_NAME"
              git config user.email "$USER_EMAIL"

              git checkout -b master

              find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
              mv _site/* .
              rm -R _site/

              git add -fA
              git commit --allow-empty -m "$(git log develop -1 --pretty=%B)"
              git push origin master -f

              echo "deployed successfully"
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy