version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    working_directory: ~/repo
    environment:
      BRANCH: develop
      TARGET_REPO: 3mmasun/3mmasun.github.io
    general:
      branches:
        only:
         - develop # list of branches to build
    steps:
      - add_ssh_keys:
          fingerprints:
            - "63:0b:bd:c0:55:56:23:f8:f1:53:99:31:14:3a:b7:d4"
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/deploy-github.sh
            else
              echo "Not develop branch, dry run only"
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
